<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="RRS.local" failures="1" tests="9" name="testClasses.TestCasesTestNG" time="36.211" errors="0" timestamp="2023-03-07T00:30:45 IST" skipped="0">
  <testcase classname="testClasses.TestCasesTestNG" name="verifytitle" time="0.033"/>
  <system-out/>
  <testcase classname="testClasses.TestCasesTestNG" name="verifylogo" time="1.916"/>
  <system-out/>
  <testcase classname="testClasses.TestCasesTestNG" name="verify_Invalid_Error_Message" time="2.429">
    <failure message="expected [Invalid credential] but found [Invalid credentials]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Invalid credential] but found [Invalid credentials]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testClasses.TestCasesTestNG.verify_Invalid_Error_Message(TestCasesTestNG.java:62)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_Invalid_Error_Message -->
  <system-out/>
  <testcase classname="testClasses.TestCasesTestNG" name="verify_Empty_Credentials" time="0.333"/>
  <system-out/>
  <testcase classname="testClasses.TestCasesTestNG" name="verify_Invalid_Credentials" time="2.092"/>
  <system-out/>
  <testcase classname="testClasses.TestCasesTestNG" name="verify_Valid_Credentials" time="4.561"/>
  <system-out/>
  <testcase classname="testClasses.TestCasesTestNG" name="verify_Admin" time="11.029"/>
  <system-out/>
  <testcase classname="testClasses.TestCasesTestNG" name="verify_All_links_DashBoard" time="12.108"/>
  <system-out/>
  <testcase classname="testClasses.TestCasesTestNG" name="verify_Dash_Profile_About_popup" time="1.710"/>
  <system-out/>
</testsuite> <!-- testClasses.TestCasesTestNG -->
